-
  version: 1.0.{build}
  platform: Any CPU
  configuration: Release
  branches:
    only:
      - release
  build:
    publish_nuget: true
  before_build:
  - cmd: nuget restore SchoolFinder\SchoolFinder.sln
  after_test:
  - cmd: nuget pack "SchoolFinder\SchoolFinder\SchoolFinder.nuspec" -Version %APPVEYOR_BUILD_VERSION%
  artifacts:
  - path: '**\*.nupkg'
    name: Command
  deploy:
  - provider: NuGet
    api_key:
      secure: IVtCkzUyoWfB41SzwMVeaYMMXwCLHjvzY7k6QW7K1GGpo8cwlN280QHWtD+qQFvp
    artifact: Command
    on:
      platform: Any CPU
      configuration: Release